python: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by python)
python: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by python)
python: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by python)
python: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by python)
python: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by python)
python: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by python)
python: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by python)
python: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by python)
python: /usr/local/ssl/lib/libcrypto.so.1.0.0: no version information available (required by python)
python: /usr/local/ssl/lib/libssl.so.1.0.0: no version information available (required by python)
Traceback (most recent call last):
  File "proxy.py", line 105, in <module>
    server = TheServer('', 9900)
  File "proxy.py", line 38, in __init__
    self.server.bind((host, port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
